# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85799a5f5e72a7e78e65d1f4967d6c52e3b5ab4313df761f9ba259a5cea2c2e234857a932da0f253eb6c8a5b1f4915f7f3f859113f77bcabcac47f3a75a3cd67
  sorcery_github_callback_url: http://0.0.0.0:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>


test:
  secret_key_base: b33d3584a0329031ba3cd39c93c591041327fcd9e74a5b9a7fcec62a8bdc352cb9ba77006b5eb26624ff99122eebb4ed496496e4e90d594bca651e32d8b2e950
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  